/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visaodatela;
import PiramideMetodos.Piramide;

/**
 *
 * @author Usuario
 */
public class PiramideTela extends javax.swing.JFrame {

    /**
     * Creates new form PiramideTela
     */
    public PiramideTela() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Panel = new javax.swing.JPanel();
        jLabel1Piramide = new javax.swing.JLabel();
        jLabel1Base = new javax.swing.JLabel();
        jLabel2Altura = new javax.swing.JLabel();
        jTextField1CampoBase = new javax.swing.JTextField();
        jTextField1CampoAltura = new javax.swing.JTextField();
        jButton1CalcularVolume = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1CampoArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1Panel.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1Panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(""), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jLabel1Piramide.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1Piramide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pyramid.png"))); // NOI18N
        jLabel1Piramide.setText("PIRAMIDE");

        javax.swing.GroupLayout jPanel1PanelLayout = new javax.swing.GroupLayout(jPanel1Panel);
        jPanel1Panel.setLayout(jPanel1PanelLayout);
        jPanel1PanelLayout.setHorizontalGroup(
            jPanel1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1PanelLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel1Piramide, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1PanelLayout.setVerticalGroup(
            jPanel1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1PanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1Piramide)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel1Base.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1Base.setText("BASE");

        jLabel2Altura.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2Altura.setText("ALTURA");

        jTextField1CampoBase.setBackground(new java.awt.Color(204, 204, 204));

        jTextField1CampoAltura.setBackground(new java.awt.Color(204, 204, 204));

        jButton1CalcularVolume.setForeground(new java.awt.Color(204, 204, 204));
        jButton1CalcularVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/maths.png"))); // NOI18N
        jButton1CalcularVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CalcularVolumeActionPerformed(evt);
            }
        });

        jTextArea1CampoArea.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1CampoArea.setColumns(20);
        jTextArea1CampoArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea1CampoArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1Base)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1CampoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2Altura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1CampoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(568, 568, 568)
                        .addComponent(jButton1CalcularVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1Base)
                            .addComponent(jTextField1CampoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2Altura)
                            .addComponent(jTextField1CampoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1CalcularVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1CalcularVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CalcularVolumeActionPerformed
        // CRIA O OBJETO
        Piramide piramidetela = new Piramide();
        
       
        piramidetela.setBase(Float.parseFloat(jTextField1CampoBase.getText()));
        piramidetela.setAltura (Float.parseFloat(jTextField1CampoAltura.getText()));
        
        
        String saida = "Dados digitados no campo: \n";
         
        saida += "BASE: " + piramidetela.getBase() + "\n";
        saida += "ALTURA: " + piramidetela.getAltura() + "\n";
        saida += "CÁLCULO DO VOLUME: " + piramidetela.calcVolume() + "\n";
       
        
        jTextArea1CampoArea.setText(saida);
        jTextField1CampoBase.setText(" "); //LIMPA O CAMPO
        jTextField1CampoAltura.setText(" "); //LIMPA O CAMPO
    }//GEN-LAST:event_jButton1CalcularVolumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PiramideTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PiramideTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PiramideTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PiramideTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PiramideTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1CalcularVolume;
    private javax.swing.JLabel jLabel1Base;
    private javax.swing.JLabel jLabel1Piramide;
    private javax.swing.JLabel jLabel2Altura;
    private javax.swing.JPanel jPanel1Panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1CampoArea;
    private javax.swing.JTextField jTextField1CampoAltura;
    private javax.swing.JTextField jTextField1CampoBase;
    // End of variables declaration//GEN-END:variables
}
