/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import javax.swing.JOptionPane;
import modelo.Eleitor;
/**
 *
 * @author Usuario
 */
public class TelaEleitor extends javax.swing.JFrame {
    Eleitor eleitor = null;//CONSTRUTOR NÃO PADRÃO 
    /**
     * Creates new form TelaEleitor
     */
    public TelaEleitor() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2EspacoAno = new javax.swing.JPanel();
        jLabel2VarNome = new javax.swing.JLabel();
        jLabel2VarAnoNasc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1EspacoAnoNascimento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Saida = new javax.swing.JTextArea();
        jButton1Executar = new javax.swing.JButton();
        jTextField1EspacoNomeCompleto1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/multiple-users-silhouette.png"))); // NOI18N
        jLabel1.setText("                TELA DO ELEITOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel2EspacoAno.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2VarNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2VarNome.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2VarNome.setText("NOME COMPLETO:");

        jLabel2VarAnoNasc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2VarAnoNasc.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2VarAnoNasc.setText("ANO DE NASCIMENTO:");

        jTextField1EspacoAnoNascimento.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1EspacoAnoNascimento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField1EspacoAnoNascimento.setForeground(new java.awt.Color(0, 0, 0));

        jTextArea1Saida.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1Saida.setColumns(20);
        jTextArea1Saida.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea1Saida.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1Saida.setRows(5);
        jTextArea1Saida.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1Saida);

        jButton1Executar.setBackground(new java.awt.Color(153, 153, 255));
        jButton1Executar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1Executar.setForeground(new java.awt.Color(0, 0, 0));
        jButton1Executar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/democracy.png"))); // NOI18N
        jButton1Executar.setText(" TIPO DE ELEITOR");
        jButton1Executar.setToolTipText("");
        jButton1Executar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ExecutarActionPerformed(evt);
            }
        });

        jTextField1EspacoNomeCompleto1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1EspacoNomeCompleto1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField1EspacoNomeCompleto1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2EspacoAnoLayout = new javax.swing.GroupLayout(jPanel2EspacoAno);
        jPanel2EspacoAno.setLayout(jPanel2EspacoAnoLayout);
        jPanel2EspacoAnoLayout.setHorizontalGroup(
            jPanel2EspacoAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2EspacoAnoLayout.createSequentialGroup()
                .addGroup(jPanel2EspacoAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2EspacoAnoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2EspacoAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2EspacoAnoLayout.createSequentialGroup()
                                .addComponent(jLabel2VarNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1EspacoNomeCompleto1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2EspacoAnoLayout.createSequentialGroup()
                                .addComponent(jLabel2VarAnoNasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1EspacoAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1Executar)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2EspacoAnoLayout.setVerticalGroup(
            jPanel2EspacoAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2EspacoAnoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2EspacoAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2VarNome)
                    .addComponent(jTextField1EspacoNomeCompleto1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel2VarAnoNasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2EspacoAnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2EspacoAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Executar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1EspacoAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );

        jButton1Executar.getAccessibleContext().setAccessibleName("          TIPO DE ELEITOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2EspacoAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2EspacoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ExecutarActionPerformed
        // TODO add your handling code here:
        try {
            eleitor = new Eleitor((jTextField1EspacoNomeCompleto1.getText()), 
            Integer.parseInt(jTextField1EspacoAnoNascimento.getText()));
            String saida = "DADOS DO ELEITOR: \n";
            saida += "NOME:" + eleitor.getNomeDoEleitor()+ "\n";
            saida += "ANO: " + eleitor.getAnoDeNascimento() + "\n";
            saida += "TIPO: " + eleitor.calcularTipoDeEleitor() + "\n";
            jTextArea1Saida.setText(saida);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButton1ExecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEleitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Executar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2VarAnoNasc;
    private javax.swing.JLabel jLabel2VarNome;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2EspacoAno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1Saida;
    private javax.swing.JTextField jTextField1EspacoAnoNascimento;
    private javax.swing.JTextField jTextField1EspacoNomeCompleto1;
    // End of variables declaration//GEN-END:variables
}
