/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import javax.swing.JOptionPane;
import modelo.ContraCheque;
/**
 *
 * @author Usuario
 */
public class TelaContraCheque extends javax.swing.JFrame {
    ContraCheque contraChequeobj = null;
    /**
     * Creates new form TelaFuncionario
     */
    public TelaContraCheque() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2Matricula = new javax.swing.JLabel();
        jLabel3NomeFuncionario = new javax.swing.JLabel();
        jLabel4SalarioBase = new javax.swing.JLabel();
        jLabel5NumeroDependentes = new javax.swing.JLabel();
        jTextField1CampoMatricula = new javax.swing.JTextField();
        jTextField1CampoNumeroDependentes = new javax.swing.JTextField();
        jTextField1CampoSalarioBase = new javax.swing.JTextField();
        jTextField1CampoNomeFuncionario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Saida = new javax.swing.JTextArea();
        jButtonExecutar = new javax.swing.JButton();
        jButtonLimparDados = new javax.swing.JButton();
        jLabelProducao = new javax.swing.JLabel();
        jTextField1CampoProducao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/atm-card.png"))); // NOI18N
        jLabel1.setText("CONTRA-CHEQUE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2Matricula.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2Matricula.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2Matricula.setText("MATRÍCULA");

        jLabel3NomeFuncionario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3NomeFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3NomeFuncionario.setText("NOME DO FUNCIONÁRIO");

        jLabel4SalarioBase.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4SalarioBase.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4SalarioBase.setText("SALÁRIO BASE");

        jLabel5NumeroDependentes.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5NumeroDependentes.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5NumeroDependentes.setText("NÚMERO DE DEPENDENTES");

        jTextField1CampoMatricula.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1CampoMatricula.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jTextField1CampoMatricula.setForeground(new java.awt.Color(0, 0, 0));

        jTextField1CampoNumeroDependentes.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1CampoNumeroDependentes.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jTextField1CampoNumeroDependentes.setForeground(new java.awt.Color(0, 0, 0));

        jTextField1CampoSalarioBase.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1CampoSalarioBase.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jTextField1CampoSalarioBase.setForeground(new java.awt.Color(0, 0, 0));

        jTextField1CampoNomeFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1CampoNomeFuncionario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jTextField1CampoNomeFuncionario.setForeground(new java.awt.Color(0, 0, 0));

        jTextArea1Saida.setColumns(20);
        jTextArea1Saida.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextArea1Saida.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1Saida.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Saida);

        jButtonExecutar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButtonExecutar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonExecutar.setText("EXECUTAR");
        jButtonExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarActionPerformed(evt);
            }
        });

        jButtonLimparDados.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButtonLimparDados.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLimparDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/eraser.png"))); // NOI18N
        jButtonLimparDados.setText(" Limpar");
        jButtonLimparDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparDadosActionPerformed(evt);
            }
        });

        jLabelProducao.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelProducao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelProducao.setText("PRODUCAO");

        jTextField1CampoProducao.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1CampoProducao.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jTextField1CampoProducao.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1CampoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1CampoNumeroDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3NomeFuncionario)
                    .addComponent(jLabel5NumeroDependentes)
                    .addComponent(jLabelProducao)
                    .addComponent(jTextField1CampoProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLimparDados)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1CampoSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonExecutar)))
                        .addGap(66, 66, 66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4SalarioBase)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2Matricula))
                    .addComponent(jTextField1CampoNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2Matricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1CampoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3NomeFuncionario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButtonExecutar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4SalarioBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1CampoSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButtonLimparDados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1CampoNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5NumeroDependentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1CampoNumeroDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelProducao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1CampoProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarActionPerformed
        // TODO add your handling code here:
        try {
            contraChequeobj = new ContraCheque(Integer.parseInt(jTextField1CampoMatricula.getText()),
            jTextField1CampoNomeFuncionario.getText(),
            Integer.parseInt(jTextField1CampoNumeroDependentes.getText()),
            Integer.parseInt(jTextField1CampoProducao.getText()),
            Float.parseFloat(jTextField1CampoSalarioBase.getText()));
            jTextArea1Saida.setText(
            "CONTRA-CHEQUE:"
            + "\nMatrícula do funcionário: " + contraChequeobj.getMatriculaDoFuncionario()
            + "\nNome do funcionário: " + contraChequeobj.getNomeDoFuncionario()
            + "\nQuantidade de dependentes: " + contraChequeobj.getNumeroDeDependentes()
            + "\nSalário base: " + contraChequeobj.getSalarioBase()
            + "\nGratificação: " + contraChequeobj.calcularGratificacaoPorProducao()
            + "\nSalário bruto: "  + contraChequeobj.calcularSalarioBruto()
            + "\nDesconto do INSS: "  + contraChequeobj.calcularImpostoDoINSS()
            + "\nDesconto do IRPF: " + contraChequeobj.calcularImpostoDoIRPF()
            + "\nDesconto dos dependentes : " + contraChequeobj.calcularDescontoDoDependente()
            + "\nSalário líquido: "  + contraChequeobj.calcularSalarioLiquido()
            );
            //DESABILITANDO BOTÕES
            jTextField1CampoMatricula.setEnabled(false);
            jTextField1CampoNomeFuncionario.setEnabled(false);
            jTextField1CampoNumeroDependentes.setEnabled(false);
            jTextField1CampoProducao.setEnabled(false);
            jTextField1CampoSalarioBase.setEnabled(false);
        } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonExecutarActionPerformed

    private void jButtonLimparDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparDadosActionPerformed
        // TODO add your handling code here:
        //EFETUANDO A LIMPEZA DE DADOS DIGITADOS
        jTextField1CampoMatricula.setText("");
        jTextField1CampoNomeFuncionario.setText("");
        jTextField1CampoNumeroDependentes.setText("");
        jTextField1CampoProducao.setText("");
        jTextField1CampoSalarioBase.setText("");
        jTextArea1Saida.setText("");
        //Reativando campo de digitação:
        jTextField1CampoMatricula.setEnabled(true);
        jTextField1CampoNomeFuncionario.setEnabled(true);
        jTextField1CampoNumeroDependentes.setEnabled(true);
        jTextField1CampoProducao.setEnabled(true);
        jTextField1CampoProducao.setEnabled(true);
        jTextArea1Saida.setText("");
    }//GEN-LAST:event_jButtonLimparDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContraCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContraCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContraCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContraCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContraCheque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExecutar;
    private javax.swing.JButton jButtonLimparDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2Matricula;
    private javax.swing.JLabel jLabel3NomeFuncionario;
    private javax.swing.JLabel jLabel4SalarioBase;
    private javax.swing.JLabel jLabel5NumeroDependentes;
    private javax.swing.JLabel jLabelProducao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1Saida;
    private javax.swing.JTextField jTextField1CampoMatricula;
    private javax.swing.JTextField jTextField1CampoNomeFuncionario;
    private javax.swing.JTextField jTextField1CampoNumeroDependentes;
    private javax.swing.JTextField jTextField1CampoProducao;
    private javax.swing.JTextField jTextField1CampoSalarioBase;
    // End of variables declaration//GEN-END:variables
}
