/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import Modelos.Paciente;
/**
 *
 * @author Usuario
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1Fichadopaciente = new javax.swing.JLabel();
        jPanel2Dados = new javax.swing.JPanel();
        jLabel1Dadospaciente = new javax.swing.JLabel();
        jLabel1Peso = new javax.swing.JLabel();
        jLabel1Nomecompleto = new javax.swing.JLabel();
        jLabel1Sexo = new javax.swing.JLabel();
        jLabel1Altura1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFieldCamponome = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextFieldCampopeso = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextFieldCampoaltura = new javax.swing.JTextArea();
        jComboBox1Sexo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Saida = new javax.swing.JTextArea();
        jButton1Botao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1Fichadopaciente.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1Fichadopaciente.setText("                  FICHA DO PACIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1Fichadopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1Fichadopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2Dados.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2Dados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1Dadospaciente.setText("Dados do Paciente:");

        jLabel1Peso.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1Peso.setText("PESO");

        jLabel1Nomecompleto.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1Nomecompleto.setText("NOME COMPLETO");

        jLabel1Sexo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1Sexo.setText("SEXO");

        jLabel1Altura1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1Altura1.setText("ALTURA");

        jTextFieldCamponome.setColumns(20);
        jTextFieldCamponome.setRows(5);
        jScrollPane2.setViewportView(jTextFieldCamponome);

        jTextFieldCampopeso.setColumns(20);
        jTextFieldCampopeso.setRows(5);
        jScrollPane3.setViewportView(jTextFieldCampopeso);

        jTextFieldCampoaltura.setColumns(20);
        jTextFieldCampoaltura.setRows(5);
        jScrollPane4.setViewportView(jTextFieldCampoaltura);

        jComboBox1Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMININO" }));

        javax.swing.GroupLayout jPanel2DadosLayout = new javax.swing.GroupLayout(jPanel2Dados);
        jPanel2Dados.setLayout(jPanel2DadosLayout);
        jPanel2DadosLayout.setHorizontalGroup(
            jPanel2DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2DadosLayout.createSequentialGroup()
                .addGroup(jPanel2DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2DadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1Dadospaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2DadosLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2DadosLayout.createSequentialGroup()
                                .addComponent(jLabel1Altura1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2DadosLayout.createSequentialGroup()
                                .addComponent(jLabel1Sexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2DadosLayout.createSequentialGroup()
                                .addComponent(jLabel1Peso)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2DadosLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(jPanel2DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2DadosLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel1Nomecompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGap(500, 500, 500)))
        );
        jPanel2DadosLayout.setVerticalGroup(
            jPanel2DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2DadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2DadosLayout.createSequentialGroup()
                        .addComponent(jLabel1Dadospaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2DadosLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1Altura1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jPanel2DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2DadosLayout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jLabel1Nomecompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(185, Short.MAX_VALUE)))
        );

        jTextArea1Saida.setBackground(new java.awt.Color(204, 255, 255));
        jTextArea1Saida.setColumns(20);
        jTextArea1Saida.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Saida);

        jButton1Botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/injecao.png"))); // NOI18N
        jButton1Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2Dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2Dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton1Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(662, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BotaoActionPerformed
        // TODO add your handling code here:
        Paciente pessoa = new Paciente(); //construtor Paciente que cria a instância do objeto que eu desejo
        pessoa.setNomeCompleto(jTextFieldCamponome.getText()); //usa get pq o texto é privado
        pessoa.setPeso(Integer.parseInt(jTextFieldCampopeso.getText()));
        pessoa.setAltura(Float.parseFloat(jTextFieldCampoaltura.getText()));
        pessoa.setSexo((String) jComboBox1Sexo.getSelectedItem());
        
        String saida = "CLÍNICA GYN \n";
        saida = saida + "DADOS DO PACIENTE \n";
        saida += "NOME COMPLETO: " + pessoa.getNomeCompleto() + "\n";
        saida += "PESO: " + pessoa.getPeso() + "\n";
        saida += "ALTURA: " + pessoa.getAltura() + "\n";
        saida += "SEXO " + pessoa.getSexo() + "\n";
        saida += "IMC: " + pessoa.calcularIMC() + "\n";
        
        jTextArea1Saida.setText(saida);
        
        jTextFieldCamponome.setText(" "); //
        jTextFieldCampopeso.setText(" ");
        jTextFieldCampoaltura.setText(" ");
        
    }//GEN-LAST:event_jButton1BotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Botao;
    private javax.swing.JComboBox<String> jComboBox1Sexo;
    private javax.swing.JLabel jLabel1Altura1;
    private javax.swing.JLabel jLabel1Dadospaciente;
    private javax.swing.JLabel jLabel1Fichadopaciente;
    private javax.swing.JLabel jLabel1Nomecompleto;
    private javax.swing.JLabel jLabel1Peso;
    private javax.swing.JLabel jLabel1Sexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2Dados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1Saida;
    private javax.swing.JTextArea jTextFieldCampoaltura;
    private javax.swing.JTextArea jTextFieldCamponome;
    private javax.swing.JTextArea jTextFieldCampopeso;
    // End of variables declaration//GEN-END:variables
}
